Repository DeeB313/Intro-To-SE-Group7, pull requests merged in 2024-02, with the labels that each got.

#20 Activity Diagrams (corrected)
  Admin.png
  Registration.png
  User-Buyer.png
Labels: invalid

#33 Adding State Diagrams for User Stories 8-12
  Diagrams/AdminBlockUser.png
  Diagrams/BuyerViewCart.png
  Diagrams/SellerContactBuyer.png
  Diagrams/UserLogOut.png
  Diagrams/UserViewAccountInfo.png
Labels: documentation

#34 Adding State Diagrams 13-15
  Diagrams/AdminMonitorUser.png
  Diagrams/BuyerBuyCart.png
  Diagrams/BuyerCompareItem.png
Labels: documentation

#35 Add Class Diagram
  Diagrams/Class Diagram.png
Labels: documentation

#15 Add diagram via upload
  uml diagram.png
Labels: enhancement

#36 Updating State Diagrams to Final Version
  Diagrams/AdminBlockUser.png
  Diagrams/BuyerViewCart.png
  Diagrams/SellerContactBuyer.png
  Diagrams/UserLogOut.png
  Diagrams/UserViewAccountInfo.png
Labels: documentation
